export default {
    email_placeholder :"Email",
    password_placeholder:"Senha",
    login_button:"Login",
    register_link:"Cadastrar",
    forgot_password_link:"Esqueceu sua senha?",
    forgot_password_confirm:"Tem certeza que deseja resetar sua senha?",
    facebook_login_button:'Facebook Login.',
    password_blank_messege:'A senha não pode ficar em braco.',
    password_alphaNumeric_check:'Para sua segurança, sua senha precisa conter pelo menos 1 número, 1 letra e ser maior que 8 dígitos.',
    password_complexity_check:'A senha precisa conter uma letra minúsula, 1 letra maiúscula, 1 número, 1 caractere especial e tamanho 6-10.',
    valid_email_check:'Por favor, digite o e-mail que deseja recuperar a senha.',
    email_not_found:'E-mail não encontrado.',
    valid_rider:"Por favor, faça login com uma conta de passageiro válida!",
    facebook_login_error:'Login Error. ',
    apple_signin_error:"Apple Signin is not set up in developer.appple.com or you have used the same email to signup already.",
    forgot_password_success_messege:'A Password Reset Link sent to your email please check and reset your New Password.',
    forgot_password_success_messege:'Um link de redefinição de senha foi enviado para seu e-mail. Por favor, verifique e crie uma nova senha.',
    facebook_login_auth_error:'Facebook Login Error:',
    google_login_auth_error:'Google Login Error:',
    static_notification_title:'Colt',
    modal_closed:'Modal fechado.',
    refferal_code_validation_modal:'Validando o seu código de referência',
    refferal_id_not_match_error:'Esse não é um código de referência válido.',
    registration_title:'Cadastro',
    first_name_placeholder:'Nome',
    first_name_blank_error:"Por favor, digite seu primeiro nome.",
    last_name_placeholder:'Sobrenome',
    last_name_blank_error:'Por favor, digite seu segundo nome.',
    login_title:'Entrar com celular',
    mobile_no_placeholder:'Insira seu número',
    mobile_no_blank_error:'Por favor, digite um número de celular válido.',
    otp_error:'Por favor, digite o código de verificação correto!',
    otp_here:'Digite o código',
    sending_otp:"Sending OTP...",
    authorize:'Confirmar',
    request_otp:"Enviar código",
    firebase_otp_error:'Authentication error with mobile OTP. Check your mobile number. You need to add International Country Code in front.',
    spacer_message:'OU CONECTE-SE COM',
    confrim_password_placeholder:'Confirmar senha',
    confrim_password_not_match_err:'Password and Confirm Password do not match',
    referral_id_placeholder:'Código de referência (Opcional)',
    register_button:'Cadastrar',
    email_exist_error:'Esse e-mail está sendo usado por outra conta.',
    Account_linking_error:'Account linking error',
    send_email_button:'Enviar e-mail',
    book_your_ride_menu:'Mapa',
    profile_setting_menu:'Perfil',
    my_wallet_menu:'Carteira',
    my_rides_menu:'Corridas',
    about_us_menu:'Sobre',
    logout:'Sair',
    photo_upload_action_sheet_title:'Escolha um tipo de mídia ?',
    camera:'Camera',
    galery:'Galeria',
    cancel:'Cancelar',
    yes:'Yes',
    network_request_failed:'Falha na conexão de rede.',
    password_update_messege:'Sua senha foi atualizada com sucesso!',
    delete_account_modal_title:'Confirmação.',
    delete_account_modal_subtitle:'Tem certeza que deseja excluir sua conta ?',
    profile_page_title:'Meu perfil',
    my_wallet_title:'Meu saldo',
    profile_page_subtitle:'Detalhes de perfil',
    location_lebel:'Localização',
    language_lebel:'Linguagem',
    preffer_language:'English',
    change_password_lebel:'Mudar senha',
    delete_account_lebel:'Excluir conta',
    change_password_modal_title:'Alterar senha?',
    old_password_placeholder:'Antiga senha',
    new_password_placeholder:'Nova senha',
    old_password_validation_error:'Por favor, digite a senha antiga',
    new_password_validation_error:'Por favor, digite a nova senha',
    update_button:'Atualizar agora',
    update_profile_title:'Atualizar perfil',
    map_screen_where_input_text:'De onde ?',
    map_screen_drop_input_text:'Para onde vamos?',
    driver_finding_alert:'Procurando motoristas pra você',
    no_driver_found_alert_title:'Alerta!',
    no_driver_found_alert_OK_button:'OK',
    congratulation:'Parabéns!',
    refferal_bonus_messege_text:'Bônus do código de referência -',
    map_screen_title:'Colt',
    cab_selection_title:'Qual categoria que deseja?',
    cab_selection_subtitle:'Selecione a categoria de carro que deseja',
    not_available:'Não disponível',
    book_now_button:'Chamar',
    contact_details:'Detalhes do contato',
    phone:'Telefone',
    my_wallet_tile:'Minha carteira',
    wallet_ballance:'Saldo da carteira',
    add_money:'Adicionar dinheiro',
    successfully:'Successfully',
    form_wallet:'form wallet',
    Transaction_Id :'Código da transação ',
    ride_list_title:'Minhas corridas',
    no_car_assign_text:'No car assign',
    not_found_text:'Não encontrado',
    you_rated_text:'Sua avaliação',
    car_no_not_found:'Placa não encontrada',
    track_now_button:'Ir pra corrida',
    bill_details_title:'Detalhes',
    your_trip:'Sua viagem',
    discount:'Desconto',
    promo_apply:'(Desconto aplicado)',
    grand_total:'Total',
    payment_status:'Status do pagamento',
    paynow_button:'Pagar agora',
    call_driver:'Ligar pro motorista',
    booked_cab_title:'Booked Cab',
    you_selected:'Você selecionou -',
    otp:'OTP :',
    driver_assign_messege:'Procurando motorista aguarde...',
    cancel_ride:'Cancelar',
    rider_cancel_text:'Passageiro cancelou',
    submit_rating:'Enviar avaliação',
    cancel_messege1:'Sua corrida',
    cancel_messege2:'foi cancelada com sucesso! ',
    dont_cancel_text:'Não cancelar',
    cancel_reason_modal_title:'Qual o motivo do cancelamento?',
    chat_title:'Chat',
    send_button_text:'Enviar',
    chat_input_title:'Converse com o motorista...',
    chat_not_found:'Chat vazio!',
    card_payment_blank_error:'Please fill up all the details properly.',
    payment_amound_error:'Payment amount is too small.',
    invalid_card_details_error:'Cartão inválido.',
    success_payment:'Pagamento concluído!',
    confrimation:'Confirmação',
    payment_alert:'Deseja deletar seu cartão ?',
    please_wait:'Por favor, aguarde...',
    enterCVV:'Digite seu CVV',
    your_promo:'Sua promoção',
    promo_exp:'Desculpe!\nO código promocional expirou!',
    promo_limit:'Desculpe!\nO código promocional atingiu o limite de uso!.',
    promo_eligiblity:'Ops, o valor da sua corrida está abaixo do necessário para essa promoção!',
    payment:'Pagamento',
    bill_details:'Detalhes',
    apply_promo:'Aplicar promoção',
    apply:"APLICAR",
    driver_near:"O motorista está próximo a você!",
    promo_discount:'Desconto da promoção',
    wallet_discount:'Desconto da carteira',
    payable_ammount:'Valor a ser pago',
    rate_ride:'Avalie seu motorista!',
    err:'Error!',
    route_not_found:'Não foi possível encontrar uma rota!',
    sorry:'Desculpe!',
    new_booking_request_push_notification:'Você tem uma nova corrida!',
    nb:'N.B.: Your fare will be increased if toll, route and destination changes or if ride took longer due to traffic orother',
    confrim_booking:'Confirmar corrida',
    estimate_fare_text:'Preço estimado da corrida',
    done:'Fim',
    notification_headerText:'Notificação',
    notification_not_found:'Sem notificações',
    location_permission:'Permissão de acesso a localização',
    ask_me_later:'Pergunte-me depois',
    min_order_value:'Valor da corrida mínima',
    add_money_tile:'Adicionar dinheiro',
    addMoneyTextInputPlaceholder:'Adicionar saldo',
    transactionFaildMsg:'Falha na transação',
    payWithCard:'Pagar com cartão ',
    CardPaymentAmount:'Pay by card',
    CashPaymentAmount:'Pay by cash',
    WalletPayment:'Pay by wallet',
    pay_mode:'Payment Mode',
    Balance:'Saldo',
    android_channel: 'Notificações',
    write_message:'Digite sua mensagem',
    terms:"Termos e Condições",
    panic_text:"Chamada de pânico",
    panic_question:"Tem certeza que deseja usar a chamada de emergência?",
    email_login:'Login',
    register_email:'Cadastre-se',
    ok:'OK',
    book_later_button:'Agendar',
    alert:'Alerta!',
    select_country:'Selecionar',
    country_blank_error:'Por favor, selecione o país',
    email_verify_message:'E-mail enviado. Por favor, verifique sua caixa de entrada',
    downloading_updates: 'Baixando atualizações...',
    checking_updates: 'Procurando atualizações...',
    fetching_data: 'Carregando...',
    loading_assets:'Carregando arquivos...'
}
