export default {
    booking_date:'Data',
    trip_start_time:'Hora do início da corrida',
    trip_end_time:'Hora do fim da corrida',
    customer_name:'Passageiro',
    car_type:'Categoria',
    vehicle_no:'Placa do carro',
    pickup_address:'Embarque',
    drop_address:'Destino',
    assign_driver:'Motorista',
    discount_ammount:'Valor do desconto',
    payment_mode:'Método',
    booking_text:'Corridas',
    image:'Imagem',
    name:'Nome',
    rate_per_km:'Taxa por KM',
    rate_per_hour:'Taxa por HORA',
    min_fare: 'Valor mínimo',
    convenience_fee:'Taxa',
    convenience_fee_percent:'Taxa (%)',
    today_text:'Hoje',
    gross_earning:'Informações gerais',
    admin_convenience_fee:'Nossos ganhos',
    this_month_text:'Mês',
    total:'Total',
    real_time_driver_section_text:'Motoristas em tempo real',
    allow_location:'Permitir localização para o mapa em tempo real.',
    sign_in:'Logar',
    email_address:'Email',
    password:'Senha',
    sign_in_error:'Erro de login. Verifique o e-mail e a senha.',
    device_type:'Tipo de dispositivo',
    user_type:'Tipo de usúario',
    title:'Título',
    body:'Corpo',
    push_notification_title:'Push Notifications',
    promo_name:'Promo Nome',
    description:'Dexrição',
    promo_type:'Promo Tipo',
    promo_discount_value:'Valor da promoção',
    max_limit:'Desconto máximo permitido',
    min_limit:'Valor mínimo do pedido',
    start_date:'Data de início',
    end_date:'Data do fim',
    promo_usage:'Contagem promocional disponível',
    promo_used_by:'Promoção usada por contagem',
    promo_offer:'Promoção e ofertas',
    refferal_bonus:'Bônus de referência',
    update_failed:'Atualização falhou',
    first_name:'Nome',
    last_name:'Sobrenome',
    email:'Email',
    mobile:'Celular',
    profile_image:'Imagem de perfil',
    vehicle_model:'Modelo do veículo',
    account_approve:'Conta aprovada',
    driver_active:'Motorista online',
    lisence_image:'Imagem da CNH',
    vehicle_number:'Placa do véiculo',
    wallet_balance:'Saldo da carteira',
    signup_via_refferal:'Inscrição por referência',
    refferal_id:'Id de referência',
    all_user:'Todos usúarios',
    notification_sent:' notificações enviadas.',
    notification_sent_failed:'Falha no envio de notificação.',
    no_user_match:'Nenhum usuário correspondeu',
    no_user_matching:'Nenhum usuário encontrado que corresponda à sua seleção.',
    dashboard_text:'Painel',
    user:'Usuários',
    promo:'Promos',
    logout:'Sair',
    driver_earning:'Ganhos do motorista',
    earning_amount:'Valor do ganho',
    driver_name:'Nome do motorista',
    driver_image:'Imagem do motorista',
    months:'Mês',
    year:'Ano',
    vehicle_type:'Placa do véiculo',
    lisence_no:'Número da CNH',
    booking_discount_earning:'Desconto da corrida',
    trip_cost_driver_share:'Ganho motorista',
    Gross_trip_cost:"Custo total da viagem",
    Discounts:"Descontos",
    Customer_paid:"Cliente pagou",
    Profit:"Lucro (Cust pago - Custo de Viagem)",
    earning_reports:'Relatórios de ganhos',
    cash_payment_amount:'Valor de pagamento em dinheiro',
    card_payment_amount:'Valor de pagamento com cartão',
    wallet_payment_amount:'Valor de pagamento da carteira',
    payment_getway:'Gateway de pagamento',
    currency_symbol: 'Símbolo da Moeda',
    currency_code: 'Código da moeda',
    settings_title:'Configurações',
    settings_label1:'Dinheiro',
    settings_label2:'Carteira',
    settings_label3:'Corrida OTP',
    settings_label4:'Aprovado',
    settings_label5:'Verificação de email obrigatória',
    payment_modes_title:'Métodos de pagamento',
    queue:'Ocupado(a)',
    createdAt: 'Criado em',
    security_title: 'Configurações de segurança',
    panic_num : 'Número de emergência',
    addbookinglable: 'Adicionar corrida',
    profile: 'Perfil',
    home:'Home',
    about_us:'Sobre',
    booking_history:'Histórico de corridas',
    notification_title:'Colt Notificação',
    select_reason:'Selecione o motivo do cancelamento',
    no_cancel_reason:'Nenhum motivo de cancelamento disponível.',
    ok:'Ok',
    cancel:'Cancelar',
    select_country:'Escolha um país',
    google_places_error:'ID de lugar para erro de localização',
    not_valid_rider:'Este login é um usuário válido, mas não e Passageiro',
    new_booking_msg:'Você tem um novo corrida',
    no_driver:'Não encontramos motoristas online',
    no_bookings:'Sem corridas disponíveis',
    booking_cancelled:'Corrida foi cancelada. ID : ',
    no_cars:'Sem carros disponíveis',
    no_route:'Nenhuma rota encontrada.',
    firstname:'Nome',
    lastname:'Sobrenome',
    phone:'Celular',
    otp:'OTP',
    profile_updated:'Perfil atualizado.',
    proper_email:'Por favor, insira o e-mail corretamente.',
    submit:'Enviar',
    booking_title:'Histórico de corridas',
    booking_id:'ID',
    booking_status: 'Status',
    trip_cost:'Valor',
    payment_status:'Status pagamento',
    cancel_booking:'Cancelar corrida',
    select_car:'Selecione o tipo de carro',
    select_proper:'Selecione corretamente.',
    must_login:'Faça login',
    pickup_location:'Endereço embarque',
    drop_location:'Endereço destino',
    booking_success:'Corrida bem-sucedida. Id da corrida: ',
    myaccount: 'Minha conta',
    login_signup: 'Login / Cadastrar',
    book_now: 'Chame agora',
    login_success:'Sucesso no login. Precisa completar o registro.',
    login_validate_error:'Email ou senha incorretos.',
    otp_validate_error:'OTP não é válido',
    reset_pass_msg:'Link de redefinição de senha enviado por e-mail.',
    signin:'Entrar',
    login:'Login',
    register:'Registrar',
    get_otp:'Pegar OTP',
    verify_otp:'Verificar OTP',
    complete_registration:'Registro completo',
    forgot_pass_title:'Esqueceu a senha',
    forgot_pass_description:'Preencha seu endereço de email e solicite. O link será enviado na sua caixa de entrada de e-mail.',
    reset_password:'Redefinir senha',
    email_tab:'Login com Email',
    phone_tab:'Login com Celular',
    select_user:'Selecionar usúario',
    other_settings:'Outras configurações',
    book_later: 'Reserve mais tarde',
    book: 'Pedir',
    booking_date_time:'Hora da corrida',
    past_booking_error:'Viagem mais tarde não está disponível para data e hora anteriores ou nos próximos 15 minutos.',
    booking_taken:'A reserva está concluída. O motorista será atribuído 15 minutos antes do horário da reserva. Seu ID de reserva é: ',
    settings_error: 'Não foi possível buscar as configurações.',
    estimate:'Preço estimado'
}