export default {
    email_placeholder :"Email",
    password_placeholder:"Password",
    login_button:"Login",
    register_link:"Cadastrar",
    forgot_password_link:"Esqueceu sua senha?",
    forgot_password_confirm:"Are you sure, you want to reset password?",
    facebook_login_button:'Facebook Login.',
    password_blank_messege:'Password cannot be blank.',
    password_alphaNumeric_check:'Password must consists of at least 1 alphanumeric characters and 8-15 length.',
    password_complexity_check:'Password must be atleast 1 small-case letter, 1 Capital letter, 1 digit, 1 special character and 6-10 length.',
    valid_email_check:'Please enter a valid email address.',
    email_not_found:'Email not found in database',
    valid_rider:"Please login with valid Rider Account",
    facebook_login_error:'Login Error. ',
    apple_signin_error:"Apple Signin is not set up in developer.appple.com or you have used the same email to signup already.",
    forgot_password_success_messege:'A Password Reset Link sent to your email please check and reset your New Password.',
    facebook_login_auth_error:'Facebook Login Error:',
    google_login_auth_error:'Google Login Error:',
    static_notification_title:'Colt Notification',
    modal_closed:'Modal has been closed.',
    refferal_code_validation_modal:'Validating your Referral Code...',
    refferal_id_not_match_error:'This is not a valid referral id.',
    registration_title:'Cadastro',
    first_name_placeholder:'Nome',
    first_name_blank_error:"Please enter your first name.",
    last_name_placeholder:'Sobrenome',
    last_name_blank_error:'Please enter your last name.',
    login_title:'Logar pelo celular',
    mobile_no_placeholder:'Número de celular',
    mobile_no_blank_error:'Please enter a valid mobile number.',
    otp_error:'Please enter the correct OTP',
    otp_here:'Please enter OTP here',
    sending_otp:"Sending OTP...",
    authorize:'Authorize',
    request_otp:"Request OTP",
    firebase_otp_error:'Authentication error with mobile OTP. Check your mobile number. You need to add International Country Code in front.',
    spacer_message:'OU CONECTE-SE COM',
    confrim_password_placeholder:'Confirm Password',
    confrim_password_not_match_err:'Password and Confirm Password do not match',
    referral_id_placeholder:'ID de referência (Opcional)',
    register_button:'Cadastrar agora',
    email_exist_error:'The email address is already in use by another account.',
    Account_linking_error:'Account linking error',
    send_email_button:'Send Email',
    book_your_ride_menu:'Mapa',
    profile_setting_menu:'Perfil',
    my_wallet_menu:'Carteira',
    my_rides_menu:'Corridas',
    about_us_menu:'Sobre',
    logout:'Sair',
    photo_upload_action_sheet_title:'Choose a Media Type ?',
    camera:'Camera',
    galery:'Gallery',
    cancel:'Cancelar',
    yes:'Yes',
    network_request_failed:'Network request failed',
    password_update_messege:'You Password successfully updated',
    delete_account_modal_title:'Confrmation',
    delete_account_modal_subtitle:'Do you want to delete your account ?',
    profile_page_title:'Meu perfil',
    my_wallet_title:'My Wallet Balance',
    profile_page_subtitle:'Profile Details',
    location_lebel:'Location',
    language_lebel:'Language',
    preffer_language:'English',
    change_password_lebel:'Change Password',
    delete_account_lebel:'Delete Account',
    change_password_modal_title:'Change Password?',
    old_password_placeholder:'Old Password',
    new_password_placeholder:'New Password',
    old_password_validation_error:'Please enter a old password',
    new_password_validation_error:'Please enter a new password',
    update_button:'Update Now',
    update_profile_title:'Atualizar perfil',
    map_screen_where_input_text:'De onde ?',
    map_screen_drop_input_text:'Para onde vamos?',
    driver_finding_alert:'Finding Drivers for you',
    no_driver_found_alert_title:'Alert!',
    no_driver_found_alert_messege:'Sorry, No Drivers found right now.Please try again later',
    no_driver_found_alert_OK_button:'OK',
    no_driver_found_alert_TRY_AGAIN_button:'Try Again',
    pickup_and_drop_location_blank_error:'Select pickup and drop location',
    pickup_location_blank_error:'Select pickup location',
    drop_location_blank_error:'Select drop location',
    car_type_blank_error:'Select car type',
    congratulation:'Congratulations!',
    refferal_bonus_messege_text:'Your referral bonus ammount -',
    map_screen_title:'Colt',
    cab_selection_title:'Qual categoria que deseja?',
    cab_selection_subtitle:'Selecione a categoria de carro que deseja',
    not_available:'Não disponível',
    book_now_button:'Chamar',
    contact_details:'Contact Details',
    phone:'Phone',
    my_wallet_tile:'Minha carteira',
    wallet_ballance:'Wallet Balance',
    add_money:'Add Money',
    transaction_history_title:'Wallet Transaction History',
    successfully:'Successfully',
    form_wallet:'form wallet',
    Transaction_Id :'Transaction Id ',
    ride_list_title:'Minhas corridas',
    no_car_assign_text:'No car assign',
    not_found_text:'Not Found',
    ride_details_page_title:'My Rides Details',
    you_rated_text:'You Rated',
    car_no_not_found:'Car Number Not found',
    track_now_button:'Track Now',
    bill_details_title:'Bill Details',
    your_trip:'Your Trip',
    discount:'Discount',
    promo_apply:'(Promo Apply)',
    grand_total:'Grand Total',
    payment_status:'Payment Status',
    paynow_button:'Pay Now',
    call_driver:'Call Driver',
    booked_cab_title:'Booked Cab',
    you_selected:'You Selected -',
    otp:'OTP :',
    driver_assign_messege:'Procurando motorista aguarde...',
    cancel_ride:'Cancelar',
    rider_cancel_text:'Passageiro cancelou',
    submit_rating:'SUBMIT RATING',
    cancel_messege1:'Your ride with Booking Id',
    cancel_messege2:'has been cancelled successfully',
    dont_cancel_text:'Não cancelar',
    cancel_reason_modal_title:'Qual o motivo do cancelamento?',
    chat_title:'Chat',
    send_button_text:'Enviar',
    chat_input_title:'Converse com o motorista...',
    chat_not_found:'Chat vazio!',
    card_payment_blank_error:'Please fill up all the details properly.',
    payment_amound_error:'Payment amount is too small.',
    invalid_card_details_error:'Card is not valid.',
    success_payment:'Pagamento concluído!',
    confrimation:'Confrimation',
    payment_alert:'Do you want to delete your card ?',
    please_wait:'Please wait...',
    enterCVV:'Please Enter Your CVV',
    your_promo:'Your promo',
    promo_exp:'Desculpe!\nO código promocional expirou!',
    promo_limit:'Desculpe!\nO código promocional atingiu o limite de uso!.',
    promo_eligiblity:'Ops, o valor da sua corrida está abaixo do necessário para essa promoção!',
    payment:'Payment',
    bill_details:'Bill Details',
    apply_promo:'Apply Promo',
    apply:"APLICAR",
    driver_near:"O motorista está próximo a você!",
    your_fare:'Your Fare',
    promo_discount:'Promo Discount',
    wallet_discount:'Wallet Discount',
    payable_ammount:'Payable Amount',
    use_wallet_balance:'Use Wallet Cash (Your balance is ',
    pay_cash:'Pay with cash',
    pay_card:'Pay with Card',
    proceed_pay:'Proceed to Pay',
    save_card:'Your Saved Cards',
    thanks:'Thanks For Rating',
    skip:'Skip',
    receipt:'Receipt',
    rate_ride:'Avalie seu motorista!',
    err:'Error!',
    route_not_found:'Não foi possível encontrar uma rota!',
    sorry:'Sorry',
    multipleBooking:'Grabcab currently doesn\'t support multiple bookings.',
    driver_not_found:'We cannot assign driver at this moment. contact to adminstrator !!',
    new_booking_request_push_notification:'You Have A New Booking Request',
    fare_details:'Fare Details',
    base_fare:'Base Fare',
    convenience_free:'Convenience Fees',
    total_fare:'Valor',
    inclusive_tax:'(Inclusive all Taxes)',
    nb:'N.B.: Your fare will be increased if toll, route and destination changes or if ride took longer due to traffic orother',
    confrim_booking:'Confirmar corrida',
    estimate_fare_text:'Preço estimado da corrida',
    done:'Done',
    notification_headerText:'Notification',
    notification_not_found:'No notification found',
    track_cab:'Track Your Cab',
    location_permission:'Location Access Permission',
    ask_me_later:'Ask Me Later',
    min_order_value:'Minimum order value-',
    add_money_tile:'Add Money',
    addMoneyTextInputPlaceholder:'Add Amount',
    transactionFaildMsg:'Transaction Failed',
    payWithCard:'Pay With Card',
    CardPaymentAmount:'Pay by card',
    CashPaymentAmount:'Pay by cash',
    WalletPayment:'Pay by wallet',
    pay_mode:'Payment Mode',
    Balance:'GrabCab Balance',
    android_channel: 'GrabCab Notifications',
    write_message:'Write your message',
    terms:"Termos e Condições",
    panic_text:"Panic Call",
    panic_question:"Do you really want to make a Panic Call?",
    email_login:'Login com Email',
    register_email:'Cadastre-se com e-mail',
    ok:'OK',
    book_later_button:'Agendar',
    past_booking_error:'Ride Later is not avaialable for Past Datetime or within next 15 mins.',
    alert:'Alerta!',
    booking_taken:'Booking is taken. Driver will be assigned 15 mins before your booking time. Your Booking ID is : ',
    select_country:'Select Country',
    country_blank_error:'Please select the country',
    email_verify_message:'Please verify your email. Email is already sent to your Inbox.',
    downloading_updates: 'Downloading Updates...',
    checking_updates: 'Checking For Updates...',
    fetching_data: 'Fetching Data...',
    loading_assets:'Loading Assets...'
}
