export default {
    about_us:'Suporte',
    contact_details:'Detalhes de contato',
    email:'Email',
    phone:'Celular',
    login_page_title:'DRIVER LOGIN',
    driver_account_approve_err:'Sua conta ainda não foi aprovada como motorista.',
    account_not_exsist:'Sua conta não existe como motorista.',
    driver_ride_complete_status:' O motorista concluiu sua viagem. seu id de reserva é',
    please_wait:'Calculating your fare',
    on_trip:'On Trip',
    complete_trip:'COMPLETE TRIP',
    account_successful_done:'Sua conta foi criada com sucesso aguarde a confirmação de aprovação, obrigado!',
    image_size_error:'O tamanho da imagem não deve ser maior que 2 MB.',
    password_blank_error:'A senha não pode ficar em branco.',
    password_complexity_alphabet:'A senha deve conter pelo menos 1 caractere alfanumérico e 8-15 caracteres.',
    password_complexity_complex:'A senha deve ter pelo menos 1 letra maiúscula, 1 letra minúscula, 1 dígito e 1 caractere especial com comprimento de 6 a 10.',
    driver_registration:'Driver Registration',
    first_name:'Primeiro nome',
    first_name_error:'Digite seu primeiro nome',
    last_name:'Sobrenome',
    last_name_error:'Digite seu sobrenome',
    email_blank_error:'Por favor insira um endereço de e-mail válido',
    mobile:'Número de celular',
    password:'Senha',
    confrim_password:'Confirme sua senha',
    password_not_match:'Senha não corresponde',
    vehicle_model_name:'Nome do modelo do veículo',
    vehicle_model_name_blank_error:'O nome do veículo não pode estar em branco',
    vehicle_reg_no:'Número de registro do veículo',
    vehicle_number_blank_err:'O número do veículo não pode estar em branco',
    upload_driving_lisence:'Envie sua carteira de motorista',
    image_size_warning:'(Tamanho da imagem: máx. 2 MB)',
    reg_no:'Registrar agora',
    update_profile:'Atualizar perfil',
    valid_mobile_number:'Por favor, coloque um número de celular válido',
    update_now:'Atualize agora',
    no_notification:'Nenhuma notificação encontrada',
    forgot_password:'Esqueceu sua senha?',
    valid_email_err:'Por favor insira um endereço de e-mail válido',
    send_email:'Enviar e-mail',
    enter_code:'Digite o código',
    submit:'Enviar',
    change_password:'Mudar senha ?',
    old_password:'Senha Antiga',
    old_password_err:'Por favor insira sua senha antiga',
    new_password:'Nova senha',
    new_password_err:'Por favor insira uma nova senha',
    update:'Atualizar',
    login:'Login',
    booking_request:'Ínicio',
    profile_settings:'Meu Perfil',
    incomeText:"Ganhos",
    my_bookings:'Corridas',
    sign_out:'Sair',
    rider_ride_cancel_text:'Rider has cancelled the ride',
    mobile_no_found:'Número de celular não encontrado',
    firebase_otp_error:'Authentication error with mobile OTP. Check your mobile number. You need to add International Country Code in front.',
    login_title:'Login with Mobile',
    mobile_no_placeholder:'Mobile Number',
    mobile_no_blank_error:'Please enter a valid mobile number.',
    otp_error:'Código de verificação incorreto.',
    otp_here:'Please enter OTP here',
    sending_otp:"Sending OTP...",
    authorize:'Authorize',
    request_otp:"Request OTP",
    driver_journey_err:'Driver started your ride. your booking id is',
    wait_for_rider:'WAIT FOR RIDER',
    rider_notified:'Rider has been notifed',
    start_trip:'START TRIP',
    cancel_reson_1:'Unable to Contact Driver',
    cancel_reson_2:'Cab is not moving in my direction',
    cancel_reson_3:'My reason is not listed',
    cancel_reson_4:'Driver Denied duty',
    cancel_reson_5:'Cab is not coming on expected time',
    api_error:'Google places API Error',
    accept_booking_request:'Accept Your Booking Request',
    pickup_location:'pickup location',
    drop_location:'drop location',
    ignore_text:'Ignore',
    modal_close:'Modal has been closed.',
    alert_text:'Alert',
    ignore_job_title:'Do you want to ignore this job?',
    cancel:'Cancel',
    ok:'OK',
    accept:'Accept',
    task_list:'Task List',
    rider_not_here:'Currently no riders in your area',
    booking_request_rejected:'Your booking request has rejected by requested driver',
    driver_requested_for_payment:'Driver has requested for payment. Your booking id is',
    driver_completed_ride:'Driver has ended trip. Please pay in Cash. Your booking id is',
    complete_ride:'COMPLETE RIDE',
    request_payment:'REQUEST PAYMENT',
    my_rides:'My Rides',
    password_reset_link:'A Password Reset Link sent to your email please check and reset your New Password.',
    notification:'Notifications',
    chat_blank:'please write something...',
    send_msg:', sent a messege to you: \n',
    driver:'Driver',
    chat_history_not_found:'Chat vazio!',
    chat:'Chat',
    send:'Send',
    type_messege:'Digite aqui sua mensagem...',
    photo_upload_action_sheet_title:'Choose a Media Type ?',
    camera:'Camera',
    galery:'Gallery',
    yes:'Yes',
    password_change:'You Password successfully updated',
    confrim:'Confrimation',
    delete_account_question:'Do you want to delete your account ?',
    my_profile:'My Profile',
    active_status:'Active Status',
    profile_details:'Profile Details',
    location:'Location',
    mobile_no:'Mobile Number',
    preffered_lang:'Preferred Language',
    lang:'English',
    delete_account:'Delete Account',
    payment_info:'Rider Payment Information',
    booking_details:'My Bookings Details',
    you_rate_text:'You have been rated',
    no_rated_text:'You have no rating',
    bill_details:'Bill Details',
    your_trip:'Your Trip',
    total_bill:'Total Bill',
    include_tax:'Includes all Taxes',
    total_payable:'My Commision',
    go_to_booking:'Go to Booking',
    my_booking:'My Bookings',
    job_ignore:'Do you want to ignore this job?',
    show_modal:'Show Modal',
    notification_title:'Colt',
    register:'Register',
    today:'Today\'s Earning',
    thismonth:'This Month\'s Earning',
    totalearning:'Total Earning',
    convenienceFee:'Convenience Fee',
    paymentStatus:'Payment Status',
    payment_mode:'Payment Mode',
    customer_payable:'Rider Payable',
    discount_amount:'Discount Amount',
    CardPaymentAmount:'Pay by card -',
    CashPaymentAmount:'Pay by cash -',
    WalletPayment:'Pay by wallet -',
    android_channel: 'Notificação Colt',
    terms:"Terms & Conditions",
    email_login:'Login with Email',
    register_email:'Register with Email',
    ok:'OK',
    spacer_message:'OR CONNECT WITH',
    password_blank_messege:'Password cannot be blank.',
    confrim_password_placeholder:'Confirm Password',
    confrim_password_not_match_err:'Password and Confirm Password do not match',
    valid_email_check:'Please enter a valid email address.',
    forgot_password_link:"Forgot or Reset Password?",
    forgot_password_confirm:"Are you sure, you want to reset password?",
    forgot_password_success_messege:'A Password Reset Link sent to your email please check and reset your New Password.',
    email_not_found:'Email not found in database',
    password_alphaNumeric_check:'Password must consists of at least 1 alphanumeric characters and 8-15 length.',
    password_complexity_check:'Password must be atleast 1 small-case letter, 1 Capital letter, 1 digit, 1 special character and 6-10 length.',
    email_placeholder :"Email",
    password_placeholder:"Password",
    login_button:"Login",
    register_link:"Register",
    car_type:'Car Type',
    upload_image_error: 'Uploaded image problem. Please try again.',
    select_country:'Select Country',
    country_blank_error:'Please select the country',
    email_verify_message:'Por favor, verifique seu e-mail. O e-mail já foi enviado para sua caixa de entrada.',
    downloading_updates: 'Baixando atualizações...',
    checking_updates: 'Verificando atualizações...',
    fetching_data: 'Buscando dados...',
    loading_assets:'Carregando arquivos...'
}